name: todoet
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animated_text_kit: ^2.0.1
  firebase_core: ^0.4.4+3
  firebase_auth: ^0.16.0
  cloud_firestore: ^0.13.5
  firebase_analytics: ^5.0.2
  firebase_storage: ^3.1.5
  image_picker: ^0.6.6+4
  modal_progress_hud: ^0.1.3
  circular_check_box: ^1.0.2
  solid_bottom_sheet: ^0.1.9
  flutter_slidable: ^0.5.4
  provider: ^4.1.2
  align_positioned: ^1.2.6
  get_it: ^4.0.2


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true


  assets:
     - images/seemly.png
     - images/task.png
     - images/Ellipse 1.png
     - images/settings.png
     - images/home.png



  fonts:
     - family: NovaRound
       fonts:
         - asset: font/NovaRound-Regular.ttf


     - family: PTSans
       fonts:
         - asset: font/PTSans-Regular.ttf

     - family: Inconsolata
       fonts:
             - asset: font/Inconsolata-VariableFont_wdth,wght.ttf


     - family: PlayfairDisplay
       fonts:
             - asset:  font/PlayfairDisplay-VariableFont_wght.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
